version: 2.1

jobs:
  lint-dockerfile-karsajobs:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project/karsajobs
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            curl -sSL -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  lint-dockerfile-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project/karsajobs-ui
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            curl -sSL -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/project/karsajobs
    steps:
      - checkout
      - run:
          name: Run Go tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build and Push for karsajobs
          command: |
            chmod +x ./karsajobs/build_push_image_karsajobs.sh
            ./karsajobs/build_push_image_karsajobs.sh

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build and Push for karsajobs-ui
          command: |
            chmod +x ./karsajobs-ui/build_push_image_karsajobs_ui.sh
            ./karsajobs-ui/build_push_image_karsajobs_ui.sh

workflows:
  version: 2

  ci-karsajobs:
    jobs:
      - lint-dockerfile-karsajobs:
          filters:
            branches:
              only: karsajobs
      - test-app:
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs:
          requires:
            - lint-dockerfile-karsajobs
            - test-app
          filters:
            branches:
              only: karsajobs

  ci-karsajobs-ui:
    jobs:
      - lint-dockerfile-karsajobs-ui:
          filters:
            branches:
              only: karsajobs-ui
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile-karsajobs-ui
          filters:
            branches:
              only: karsajobs-ui
